import { Dimensions, StyleSheet } from 'react-native';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 60,
    backgroundColor: '#f8f9fa',
  },
  centerContent: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 20,
    paddingVertical: 20,
    minHeight: '100%',
  },

  header: {
    alignItems: 'center',
    marginBottom: 10,
    marginTop: 5,
    width: '100%',
  },
  title: {
    fontSize: 42,
    fontWeight: '800',
    color: '#2c3e50',
    marginBottom: 8,
    textShadowColor: 'rgba(0,0,0,0.15)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 8,
    letterSpacing: 1,
  },
  subtitle: {
    fontSize: 18,
    color: '#7f8c8d',
    textAlign: 'center',
    fontWeight: '500',
    fontStyle: 'italic',
    width: '100%',
    paddingHorizontal: 10,
    lineHeight: 24,
  },

  // instructions box
  instructionBox: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 20,
    paddingVertical: 25,
    paddingHorizontal: 25,
    marginVertical: 20,
    width: '95%',
    maxWidth: 420,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 15,
    elevation: 6,
    borderWidth: 2,
    borderColor: 'rgba(52, 152, 219, 0.2)',
  },
  instructionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#2c3e50',
    textAlign: 'center',
    marginBottom: 15,
    letterSpacing: 0.5,
  },
  instructionText: {
    fontSize: 16,
    color: '#34495e',
    lineHeight: 24,
    textAlign: 'left',
    marginBottom: 20,
    fontWeight: '500',
  },
  resetButtonInstructions: {
    backgroundColor: '#95a5a6',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  resetButtonInstructionsText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0.3,
  },

  // short instructions - minimal text under mic button
  shortInstructions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 15,
    marginBottom: 20,
    paddingHorizontal: 20,
    width: '90%',
    maxWidth: 350,
  },
  shortInstructionsText: {
    fontSize: 14,
    color: '#7f8c8d',
    fontWeight: '500',
    flex: 1,
    textAlign: 'center',
  },
  smallResetButton: {
    backgroundColor: '#95a5a6',
    borderRadius: 15,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  smallResetButtonText: {
    fontSize: 14,
    color: '#ffffff',
  },

  statusCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 25,
    paddingVertical: 20,
    paddingHorizontal: 30,
    marginVertical: 15,
    width: '90%',
    maxWidth: 400,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 8,
    borderWidth: 2,
    borderColor: 'rgba(52, 152, 219, 0.15)',
  },
  statusText: {
    fontSize: 18,
    color: '#2c3e50',
    textAlign: 'center',
    fontWeight: '600',
    lineHeight: 24,
  },

  controlSection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 20,
    width: '100%',
    paddingHorizontal: 20,
  },

  // microphone bnutton
  micButton: {
    backgroundColor: '#3498db',
    borderRadius: 40,
    paddingVertical: 30,
    paddingHorizontal: 30,
    marginVertical: 25,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#3498db',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 10,
    borderWidth: 4,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    minWidth: 140,
    minHeight: 140,
    transform: [{ scale: 1 }],
  },
  micButtonListening: {
    backgroundColor: '#e74c3c',
    shadowColor: '#e74c3c',
    borderColor: 'rgba(255, 255, 255, 0.3)',
    transform: [{ scale: 1.05 }],
  },
  micButtonText: {
    fontSize: 28,
    marginBottom: 6,
  },
  micButtonSubtext: {
    fontSize: 12,
    color: '#ffffff',
    fontWeight: '600',
    textAlign: 'center',
    letterSpacing: 0.3,
  },

  stateBox: {
    backgroundColor: 'rgba(46, 204, 113, 0.15)',
    borderRadius: 16,
    padding: 20,
    marginVertical: 15,
    width: '100%',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(46, 204, 113, 0.3)',
  },
  stateText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#27ae60',
    textAlign: 'center',
    letterSpacing: 0.5,
  },

  combinedStatusBox: {
    backgroundColor: 'rgba(142, 68, 173, 0.15)',
    borderRadius: 18,
    paddingVertical: 15,
    paddingHorizontal: 20,
    marginVertical: 15,
    width: '90%',
    maxWidth: 380,
    borderWidth: 1,
    borderColor: 'rgba(142, 68, 173, 0.25)',
    shadowColor: 'rgba(142, 68, 173, 0.3)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 3,
  },
  combinedStatusText: {
    fontSize: 15,
    color: '#8e44ad',
    fontWeight: '600',
    textAlign: 'center',
    marginVertical: 3,
    letterSpacing: 0.3,
  },

  resultBox: {
    backgroundColor: 'rgba(155, 89, 182, 0.1)',
    borderRadius: 16,
    padding: 20,
    marginVertical: 15,
    width: '100%',
    borderWidth: 1,
    borderColor: 'rgba(155, 89, 182, 0.2)',
  },
  resultLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#8e44ad',
    marginBottom: 8,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  resultText: {
    fontSize: 16,
    color: '#2c3e50',
    textAlign: 'center',
    fontWeight: '500',
    fontStyle: 'italic',
  },

  buttonContainer: {
    width: '100%',
    alignItems: 'center',
    marginTop: 20,
  },
  testButtonsContainer: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 20,
  },
  testButtonsTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#34495e',
    marginBottom: 15,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  testButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    maxWidth: 300,
  },
  testButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 100,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  blueButton: {
    backgroundColor: '#3498db',
  },
  redButton: {
    backgroundColor: '#e74c3c',
  },
  testButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0.5,
  },

  resetButton: {
    backgroundColor: '#95a5a6',
    borderRadius: 30,
    width: 60,
    height: 60,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  resetButtonText: {
    fontSize: 24,
    color: '#ffffff',
  },

  resetText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  loadingText: {
    fontSize: 18,
    color: '#34495e',
    textAlign: 'center',
    marginTop: 20,
  },
});