import { Dimensions, StyleSheet } from 'react-native';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 60,
    backgroundColor: '#000000',
  },
  centerContent: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  content: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 20,
    paddingVertical: 20,
    paddingBottom: 60,
  },

  headerContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 30,
    marginTop: 20,
    marginBottom: 25,
    paddingVertical: 30,
    paddingHorizontal: 25,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 12,
    width: '90%',
    maxWidth: 400,
    alignSelf: 'center',
  },
  header: {
    alignItems: 'center',
    width: '100%',
  },
  logoContainer: {
    marginBottom: 20,
    shadowColor: '#c65b5b',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 15,
    elevation: 10,
    borderRadius: 80,
    padding: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  titleContainer: {
    alignItems: 'center',
    marginTop: 10,
    width: '100%',
    paddingHorizontal: 10,
  },
  title: {
    fontSize: 36,
    fontWeight: '200',
    color: '#FFFFFF',
    marginBottom: 5,
    textShadowColor: 'rgba(255,255,255,0.3)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
    letterSpacing: 3,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 18,
    color: 'rgba(255,255,255,0.8)',
    textAlign: 'center',
    fontWeight: '200',
    fontStyle: 'italic',
    lineHeight: 26,
    letterSpacing: 1.5,
    textShadowColor: 'rgba(255,255,255,0.2)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
    flexShrink: 0,
    minWidth: 200,
  },

  // instructions is part of header
  headerInstructions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 20,
    paddingTop: 20,
    paddingHorizontal: 5,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
  },
  headerInstructionsText: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.7)',
    fontWeight: '300',
    flex: 1,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  headerResetButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 15,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  headerResetButtonText: {
    fontSize: 14,
    color: '#ffffff',
  },

  // instructions box
  instructionBox: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 20,
    paddingVertical: 25,
    paddingHorizontal: 25,
    marginVertical: 20,
    width: '95%',
    maxWidth: 420,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 15,
    elevation: 6,
    borderWidth: 2,
    borderColor: 'rgba(52, 152, 219, 0.2)',
  },
  instructionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#2c3e50',
    textAlign: 'center',
    marginBottom: 15,
    letterSpacing: 0.5,
  },
  instructionText: {
    fontSize: 16,
    color: '#34495e',
    lineHeight: 24,
    textAlign: 'left',
    marginBottom: 20,
    fontWeight: '500',
  },
  resetButtonInstructions: {
    backgroundColor: '#95a5a6',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  resetButtonInstructionsText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0.3,
  },

  // short instructions - minimal text under mic button
  shortInstructions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 15,
    marginBottom: 20,
    paddingHorizontal: 20,
    width: '90%',
    maxWidth: 350,
  },
  shortInstructionsText: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.7)',
    fontWeight: '300',
    flex: 1,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  smallResetButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 15,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  smallResetButtonText: {
    fontSize: 14,
    color: '#ffffff',
  },

  statusCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 25,
    paddingVertical: 20,
    paddingHorizontal: 30,
    marginVertical: 15,
    width: '90%',
    maxWidth: 400,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  statusText: {
    fontSize: 16,
    color: '#FFFFFF',
    textAlign: 'center',
    fontWeight: '400',
    lineHeight: 24,
    letterSpacing: 0.5,
  },

  controlSection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 20,
    width: '100%',
    paddingHorizontal: 20,
  },

  // microphone button
  micButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 80,
    paddingVertical: 30,
    paddingHorizontal: 30,
    marginVertical: 25,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#FFFFFF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 15,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    minWidth: 160,
    minHeight: 160,
    position: 'relative',
  },
  micButtonListening: {
    backgroundColor: 'rgba(52, 152, 219, 0.3)',
    shadowColor: '#3498db',
    shadowOpacity: 0.6,
    shadowRadius: 30,
    borderColor: 'rgba(52, 152, 219, 0.5)',
    transform: [{ scale: 1.1 }],
  },
  micButtonText: {
    fontSize: 32,
    marginBottom: 8,
    textShadowColor: 'rgba(255, 255, 255, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  micButtonSubtext: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.9)',
    fontWeight: '300',
    textAlign: 'center',
    letterSpacing: 1,
    textShadowColor: 'rgba(255, 255, 255, 0.3)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
  },

  stateBox: {
    backgroundColor: 'rgba(46, 204, 113, 0.15)',
    borderRadius: 16,
    padding: 20,
    marginVertical: 15,
    width: '100%',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(46, 204, 113, 0.3)',
  },
  stateText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#27ae60',
    textAlign: 'center',
    letterSpacing: 0.5,
  },

  combinedStatusBox: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 20,
    paddingVertical: 18,
    paddingHorizontal: 25,
    marginTop: 20,
    marginBottom: 40,
    width: '90%',
    maxWidth: 380,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  combinedStatusText: {
    fontSize: 15,
    color: 'rgba(255, 255, 255, 0.9)',
    fontWeight: '300',
    textAlign: 'center',
    marginVertical: 4,
    letterSpacing: 0.5,
  },

  resultBox: {
    backgroundColor: 'rgba(155, 89, 182, 0.1)',
    borderRadius: 16,
    padding: 20,
    marginVertical: 15,
    width: '100%',
    borderWidth: 1,
    borderColor: 'rgba(155, 89, 182, 0.2)',
  },
  resultLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#8e44ad',
    marginBottom: 8,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  resultText: {
    fontSize: 16,
    color: '#2c3e50',
    textAlign: 'center',
    fontWeight: '500',
    fontStyle: 'italic',
  },

  buttonContainer: {
    width: '100%',
    alignItems: 'center',
    marginTop: 20,
  },
  testButtonsContainer: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 20,
  },
  testButtonsTitle: {
    fontSize: 14,
    fontWeight: '300',
    color: 'rgba(255, 255, 255, 0.6)',
    marginBottom: 20,
    textAlign: 'center',
    letterSpacing: 1,
  },
  testButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    maxWidth: 300,
  },
  testButton: {
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 110,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  blueButton: {
    backgroundColor: 'rgba(52, 152, 219, 0.3)',
  },
  redButton: {
    backgroundColor: 'rgba(231, 76, 60, 0.3)',
  },
  testButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '300',
    letterSpacing: 0.8,
  },

  resetButton: {
    backgroundColor: '#95a5a6',
    borderRadius: 30,
    width: 60,
    height: 60,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  resetButtonText: {
    fontSize: 24,
    color: '#ffffff',
  },

  resetText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  loadingText: {
    fontSize: 18,
    color: '#34495e',
    textAlign: 'center',
    marginTop: 20,
  },
});