#!/usr/bin/env bash

set -e

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOTDIR="$(git -C "$SCRIPTDIR" rev-parse --show-toplevel)"

set -x

# generate AUTHORS file
cat > "${ROOTDIR}/AUTHORS" <<- EOF
	# file @generated by authors/generate-authors.sh. DO NOT EDIT.
	# this file lists all contributors to the repository.
	# see authors/generate-authors.sh to make modifications.

	$(git -C "$ROOTDIR" log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf)
EOF
